{
 "title": "Sovereign Celestia Adapter",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "query": "influxdb" },
   { "name": "LOKI_DS", "query": "loki" },
   { "name": "bucket", "query": { "query": "buckets()" } },
   {
    "name": "host",
    "query": {
     "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"host\",\n    predicate: (r) => true,\n    start: -1d\n)"
    }
   },
   { "name": "agg_func", "label": "Aggregation function", "query": "raw,mean,median,p90,p99,max" },
   {
    "name": "agg_interval",
    "label": "Aggregation Interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Adapter Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Calls Success Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) =>\n      (r._measurement == \"sov_celestia_adapter_header_get_by_height\" \n      or r._measurement == \"sov_celestia_adapter_header_network_head\"\n      or r._measurement == \"sov_celestia_adapter_share_get_namespace_data\"\n      or r._measurement == \"sov_celestia_adapter_state_submit_pay_for_blob\"\n      or r._measurement == \"sov_celestia_adapter_blob_get_all\")\n  )\n  |> map(fn: (r) => ({\n    r with\n    success: if r[\"is_success\"] == \"1\" then 1.0 else 0.0,\n    total: 1.0\n  }))\n  |> group()\n  |> reduce(\n    identity: {success: 0.0, total: 0.0},\n    fn: (r, accumulator) => ({\n      success: accumulator.success + r.success,\n      total: accumulator.total + r.total\n    })\n  )\n  |> map(fn: (r) => ({\n    _value: (r.success / r.total) * 100.0\n  }))"
    }
   ]
  },
  {
   "title": "Avg. API Calls Per Minute",
   "type": "stat",
   "description": "For all API calls",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) =>\n      (r._measurement == \"sov_celestia_adapter_header_get_by_height\" \n      or r._measurement == \"sov_celestia_adapter_header_network_head\"\n      or r._measurement == \"sov_celestia_adapter_share_get_namespace_data\"\n      or r._measurement == \"sov_celestia_adapter_state_submit_pay_for_blob\"\n      or r._measurement == \"sov_celestia_adapter_blob_get_all\")\n      and r._field == \"response_time_us\"\n  )\n  |> group()\n  |> count()\n  |> map(fn: (r) => ({\n      r with _value: float(v: r._value) / float(v: uint(v: v.timeRangeStop) - uint(v: v.timeRangeStart)) * 60000000000.0\n  }))"
    }
   ]
  },
  {
   "title": "Avg. Blob Throughput",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r._measurement == \"sov_celestia_adapter_submit_blob\" and r._field == \"bytes\")\n  |> sum()\n  |> map(fn: (r) => ({\n      r with _value: r._value / float(v: int(v: v.timeRangeStop) - int(v: v.timeRangeStart)) * 1000000000.0\n  }))"
    }
   ]
  },
  {
   "title": "Blob data submitted",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r._measurement == \"sov_celestia_adapter_submit_blob\" and r._field == \"bytes\")\n  |> sum()"
    }
   ]
  },
  {
   "title": "Batch Blobs Submitted",
   "type": "stat",
   "description": "Successful batch blob submission",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) =>\n    r._measurement == \"sov_celestia_adapter_submit_blob\"\n    and r[\"namespace\"] == \"batch\" and r._field == \"bytes\"\n  )\n  |> count()"
    }
   ]
  },
  {
   "title": "Batch Submission Success Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) =>\n    r._measurement == \"sov_celestia_adapter_state_submit_pay_for_blob\"\n    and r[\"namespace\"] == \"batch\"\n  )\n  |> map(fn: (r) => ({\n    r with\n    success: if r[\"is_success\"] == \"1\" then 1.0 else 0.0,\n    total: 1.0\n  }))\n  |> group()\n  |> reduce(\n    identity: {success: 0.0, total: 0.0},\n    fn: (r, accumulator) => ({\n      success: accumulator.success + r.success,\n      total: accumulator.total + r.total\n    })\n  )\n  |> map(fn: (r) => ({\n    _value: (r.success / r.total) * 100.0\n  }))"
    }
   ]
  },
  {
   "title": "Proof Blobs Submitted",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) =>\n    r._measurement == \"sov_celestia_adapter_submit_blob\"\n    and r[\"namespace\"] == \"proof\" and r._field == \"bytes\"\n  )\n  |> count()"
    }
   ]
  },
  {
   "title": "Proof Submission Success Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) =>\n    r._measurement == \"sov_celestia_adapter_state_submit_pay_for_blob\"\n    and r[\"namespace\"] == \"proof\"\n  )\n  |> map(fn: (r) => ({\n    r with\n    success: if r[\"is_success\"] == \"1\" then 1.0 else 0.0,\n    total: 1.0\n  }))\n  |> group()\n  |> reduce(\n    identity: {success: 0.0, total: 0.0},\n    fn: (r, accumulator) => ({\n      success: accumulator.success + r.success,\n      total: accumulator.total + r.total\n    })\n  )\n  |> map(fn: (r) => ({\n    _value: (r.success / r.total) * 100.0\n  }))"
    }
   ]
  },
  {
   "title": "API Calls",
   "type": "timeseries",
   "description": "Response time of individual API call",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "query": "agg_func = \"${agg_func}\"\n\ndata = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r.host == \"${host}\" \n    and (\n      r._measurement == \"sov_celestia_adapter_header_get_by_height\" \n      or r._measurement == \"sov_celestia_adapter_header_network_head\"\n      or r._measurement == \"sov_celestia_adapter_share_get_namespace_data\"\n      or r._measurement == \"sov_celestia_adapter_state_submit_pay_for_blob\"\n      or r._measurement == \"sov_celestia_adapter_blob_get_all\"\n      )\n  )\n  |> drop(columns: [\"host\"])\n\n\nif agg_func == \"raw\" then\n  data\nelse if agg_func == \"median\" then\n  data |> aggregateWindow(every: ${agg_interval}, fn: median)\nelse if agg_func == \"mean\" then\n  data |> aggregateWindow(every: ${agg_interval}, fn: mean)\nelse if agg_func == \"p90\" then\n  data |> aggregateWindow(every: ${agg_interval}, fn: (column, tables=<-) => tables |> quantile(q: 0.90, column: column))\nelse if agg_func == \"p99\" then\n  data |> aggregateWindow(every: ${agg_interval}, fn: (column, tables=<-) => tables |> quantile(q: 0.99, column: column))\nelse if agg_func == \"max\" then\n  data |> aggregateWindow(every: ${agg_interval}, fn: (column, tables=<-) => tables |> quantile(q: 1.0, column: column))\nelse\n  data |> aggregateWindow(every: ${agg_interval}, fn: median)"
    }
   ]
  },
  {
   "title": "Submit Blob Times",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "query": "agg_func = \"${agg_func}\"\n\ndata = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r.host == \"${host}\" \n    and r._measurement == \"sov_celestia_adapter_submit_blob\"\n    and r._field != \"namespace\"\n    and r._field != \"da_height\"\n  )\n  |> group(columns: [\"_field\"])\n\nif agg_func == \"raw\" then\n  data\nelse if agg_func == \"median\" then\n  data |> aggregateWindow(every: ${agg_interval}, fn: median)\nelse if agg_func == \"mean\" then\n  data |> aggregateWindow(every: ${agg_interval}, fn: mean)\nelse if agg_func == \"p90\" then\n  data |> aggregateWindow(every: ${agg_interval}, fn: (column, tables=<-) => tables |> quantile(q: 0.90, column: column))\nelse if agg_func == \"p99\" then\n  data |> aggregateWindow(every: ${agg_interval}, fn: (column, tables=<-) => tables |> quantile(q: 0.99, column: column))\nelse if agg_func == \"max\" then\n  data |> aggregateWindow(every: ${agg_interval}, fn: (column, tables=<-) => tables |> quantile(q: 1.0, column: column))\nelse\n  data |> aggregateWindow(every: ${agg_interval}, fn: median)"
    }
   ]
  },
  {
   "title": "API Calls per minute",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "query": "agg_func = \"${agg_func}\"\n\ndata = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r.host == \"${host}\" \n    and (\n      r._measurement == \"sov_celestia_adapter_header_get_by_height\" \n      or r._measurement == \"sov_celestia_adapter_header_network_head\"\n      or r._measurement == \"sov_celestia_adapter_share_get_namespace_data\"\n      or r._measurement == \"sov_celestia_adapter_state_submit_pay_for_blob\"\n      or r._measurement == \"sov_celestia_adapter_blob_get_all\"\n      )\n  )\n  |> drop(columns: [\"host\", \"namespace\"])\n  |> group(columns: [\"_measurement\", \"is_success\"], mode: \"by\")\n  |> aggregateWindow(\n      every: 30s,\n      fn: count,\n      createEmpty: false\n  )\n  |> map(fn: (r) => ({\n      r with\n      _value: float(v: r._value) * 2.0\n  }))\n\nif agg_func == \"raw\" then\n  data\nelse if agg_func == \"median\" then\n  data |> aggregateWindow(every: ${agg_interval}, fn: median)\nelse if agg_func == \"mean\" then\n  data |> aggregateWindow(every: ${agg_interval}, fn: mean)\nelse\n  data |> aggregateWindow(every: ${agg_interval}, fn: mean)"
    }
   ]
  },
  {
   "title": "Fetch Block Times",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "query": "agg_func = \"${agg_func}\"\n\ndata = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r.host == \"${host}\" \n    and r._measurement == \"sov_celestia_adapter_get_block\"  \n    and r._field != \"height\" \n    and r._field != \"square_width\" \n    and r._field != \"batch_rows\" \n    and r._field != \"batch_shares\"\n    and r._field != \"proof_rows\" \n    and r._field != \"proof_shares\"\n  )\n  |> group(columns: [\"_field\"])\n\nif agg_func == \"raw\" then\n  data\nelse if agg_func == \"median\" then\n  data |> aggregateWindow(every: ${agg_interval}, fn: median)\nelse if agg_func == \"mean\" then\n  data |> aggregateWindow(every: ${agg_interval}, fn: mean)\nelse if agg_func == \"p90\" then\n  data |> aggregateWindow(every: ${agg_interval}, fn: (column, tables=<-) => tables |> quantile(q: 0.90, column: column))\nelse if agg_func == \"p99\" then\n  data |> aggregateWindow(every: ${agg_interval}, fn: (column, tables=<-) => tables |> quantile(q: 0.99, column: column))\nelse if agg_func == \"max\" then\n  data |> aggregateWindow(every: ${agg_interval}, fn: (column, tables=<-) => tables |> quantile(q: 1.0, column: column))\nelse\n  data |> aggregateWindow(every: ${agg_interval}, fn: median)"
    }
   ]
  },
  {
   "title": "Fetched Block Squares",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "query": "agg_func = \"${agg_func}\"\n\ndata = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r.host == \"${host}\" \n    and r._measurement == \"sov_celestia_adapter_get_block\"  \n    and r._field != \"height\" \n    and r._field != \"square_width\" \n    and r._field != \"total_time_us\" \n    and r._field != \"fetch_header_us\"\n    and r._field != \"futures_us\" \n    and r._field != \"build_data_us\"\n  )\n  |> group(columns: [\"_field\"])\n\nif agg_func == \"raw\" then\n  data\nelse if agg_func == \"median\" then\n  data |> aggregateWindow(every: ${agg_interval}, fn: median)\nelse if agg_func == \"mean\" then\n  data |> aggregateWindow(every: ${agg_interval}, fn: mean)\nelse if agg_func == \"p90\" then\n  data |> aggregateWindow(every: ${agg_interval}, fn: (column, tables=<-) => tables |> quantile(q: 0.90, column: column))\nelse if agg_func == \"p99\" then\n  data |> aggregateWindow(every: ${agg_interval}, fn: (column, tables=<-) => tables |> quantile(q: 0.99, column: column))\nelse if agg_func == \"max\" then\n  data |> aggregateWindow(every: ${agg_interval}, fn: (column, tables=<-) => tables |> quantile(q: 1.0, column: column))\nelse\n  data |> aggregateWindow(every: ${agg_interval}, fn: median)"
    }
   ]
  }
 ]
}