{
 "title": "Hyperlane Relayer Overview",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Messages Processed",
   "type": "timeseries",
   "description": "There shouldn't be abrupt changes, especially for a specific pair",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (origin,remote)(round(increase(hyperlane_messages_processed_count[5m])))",
     "legendFormat": "{{hyperlane_deployment}}: {{origin}}->{{remote}}"
    }
   ]
  },
  {
   "title": "Prepare queues (all)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (remote, queue_name)(\n    hyperlane_submitter_queue_length{queue_name=\"prepare_queue\"}\n)",
     "legendFormat": "{{hyperlane_deployment }} - {{remote}}"
    }
   ]
  },
  {
   "title": "Submit Queues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(remote, queue_name) (hyperlane_submitter_queue_length{queue_name=\"submit_queue\"})",
     "legendFormat": "{{remote}}"
    }
   ]
  },
  {
   "title": "Confirm Queues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(remote, queue_name) (avg_over_time(hyperlane_submitter_queue_length{queue_name=\"confirm_queue\"}[20m]))",
     "legendFormat": "{{remote}}"
    }
   ]
  }
 ]
}