{
 "title": "Validator Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "chain", "label": "Origin Chain", "query": { "query": "label_values(chain)" } }
  ]
 },
 "panels": [
  {
   "title": "Signed Checkpoint Diffs (30m)",
   "type": "timeseries",
   "description": "The number of signed checkpoints during last 30 minutes. If the metric is zero, it is worth to check if the validator makes any progress. If the metrics is huge, probably, validator is catching up with the chain. It is worth a check as well.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(chain) (increase (hyperlane_latest_checkpoint{\n    agent=\"validator\", \n    phase=\"validator_processed\",\n    chain=~\"${chain:regex}\"\n}[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Diff observed - processed checkpoints",
   "type": "timeseries",
   "description": "This metric is the difference between the number of observed checkpoints and the number of processed (signed and published) checkpoints. The metric may be positive for a short period of time. If the metric is positive for an extended period time, it indicate an issue with signing and publishing checkpoints.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max by(chain) (hyperlane_latest_checkpoint{\n    agent=\"validator\", \n    phase=\"validator_observed\",\n    chain=~\"${chain:regex}\"\n})\n-\nmax by(chain) (hyperlane_latest_checkpoint{\n    agent=\"validator\", \n    phase=\"validator_processed\",\n    chain=~\"${chain:regex}\"\n})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Block Diffs (30m)",
   "type": "timeseries",
   "description": "This metric reports the number of blocks confirmed by a chain during last 30 mins. This metric is updated every 60 seconds directly from RPC endpoint. Depending on an average block confirmation time, this metrics should follow what is happening on the chain.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by (chain) (increase(hyperlane_block_height{agent=\"validator\", chain=~\"${chain:regex}\"}[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Contract Sync Liveness",
   "type": "timeseries",
   "description": "This metrics grows as validator synchronizes with chain. The values of the metrics is the current timestamp of the last iteration done by the validator. If the metrics is constant, it means that validator does not make any progress and the issue should be investigated.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max by(chain) (hyperlane_contract_sync_liveness{\n    agent=\"validator\", \n    chain=~\"${chain:regex}\"\n})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Contract Sync Block Diffs (30m)",
   "type": "timeseries",
   "description": "The metric reports the number of blocks indexed by validator during last 30 minutes. It should approximately match the number of blocks produced by the chain during last 30 minutes. If the metric deviate significantly in any direction, becomes zero, it should be investigated.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max by (chain) (increase(hyperlane_contract_sync_block_height{agent=\"validator\", chain=~\"${chain:regex}\"}[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cursor Block Diffs (30m)",
   "type": "timeseries",
   "description": "The metric reports the number of blocks indexed by validator during last 30 minutes. It should approximately match the number of blocks produced by the chain during last 30 minutes. If the metric deviate significantly in any direction, becomes zero, it should be investigated.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "max by (chain) (increase(hyperlane_cursor_current_block{agent=\"validator\", cursor_type=\"forward_sequenced\", chain=~\"${chain:regex}\"}[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error log count diffs (30m)",
   "type": "timeseries",
   "description": "This metric report the number of errors in the log of validator. If there is an unexplained spike, it should be investigated.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "max by (pod) (increase(hyperlane_span_events_total{\n    agent=\"validator\", \n    event_level=\"error\",\n    app_kubernetes_io_instance=~\"${chain:regex}-.*\"\n}[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Warning log count diffs (30m)",
   "type": "timeseries",
   "description": "This metric report the number of warnings in the log of validator. If there is an unexplained spike, it should be investigated.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "max by (pod) (increase(hyperlane_span_events_total{agent=\"validator\", event_level=\"warn\", app_kubernetes_io_instance=~\"${chain:regex}-.*\"}[30m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}